name: kaede
services:
  bot:
    container_name: kaede
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:3000
    env_file:
      - .env
    volumes:
      - ./dbs:/app/dbs
