import { create_category, mention } from './util';

export const single_user = [
	// new
	create_category({
		type: 'gif',
		category: 'smug',
		desc: 'Smug',
		mentioning: false,
		cb: (v) => `${mention(v)} is smugging 😏`,
	}),
	create_category({
		type: 'gif',
		category: 'wink',
		desc: 'Wink',
		mentioning: false,
		cb: (v) => `${mention(v)} is winking 😉`,
	}),
	create_category({
		type: 'gif',
		category: 'blush',
		desc: 'Blush',
		mentioning: false,
		cb: (v) => `${mention(v)} is blushing 😳`,
	}),
	create_category({
		type: 'gif',
		category: 'bored',
		desc: 'Bored',
		mentioning: false,
		cb: (v) => `${mention(v)} is bored 😑`,
	}),
	create_category({
		type: 'gif',
		category: 'cry',
		desc: 'Cry',
		mentioning: false,
		cb: (v) => `${mention(v)} is crying 😞`,
	}),
	create_category({
		type: 'gif',
		category: 'happy',
		desc: 'Happy',
		mentioning: false,
		cb: (v) => `${mention(v)} is happy 😄`,
	}),
	create_category({
		type: 'gif',
		category: 'lurk',
		desc: 'Lurk',
		mentioning: false,
		cb: (v) => `${mention(v)} is lurking 👀`,
	}),
	create_category({
		type: 'gif',
		category: 'thumbsup',
		desc: 'Thumbs Up',
		mentioning: false,
		cb: (v) => `${mention(v)} is giving a thumbs up 👍`,
	}),

	// old
	create_category({
		type: 'gif',
		category: 'smile',
		desc: 'Smile',
		mentioning: false,
		cb: (v) => `${mention(v)} is smiling 😊`,
	}),
	create_category({
		type: 'gif',
		category: 'wave',
		desc: 'Wave',
		mentioning: false,
		cb: (v) => `${mention(v)} is waving 👋`,
	}),
	create_category({
		type: 'gif',
		category: 'stare',
		desc: 'Stare',
		mentioning: false,
		cb: (v) => `${mention(v)} is staring 👀`,
	}),
	create_category({
		type: 'gif',
		category: 'shrug',
		desc: 'Shrug',
		mentioning: false,
		cb: (v) => `${mention(v)} is shrugging 🤷`,
	}),
	create_category({
		type: 'gif',
		category: 'think',
		desc: 'Think',
		mentioning: false,
		cb: (v) => `${mention(v)} is thinking 🤔`,
	}),
	create_category({
		type: 'gif',
		category: 'yawn',
		desc: 'Yawn',
		mentioning: false,
		cb: (v) => `${mention(v)} is yawning 😴`,
	}),
	create_category({
		type: 'gif',
		category: 'laugh',
		desc: 'Laugh',
		mentioning: false,
		cb: (v) => `${mention(v)} is laughing 😂`,
	}),
	create_category({
		type: 'gif',
		category: 'nod',
		desc: 'Nod',
		mentioning: false,
		cb: (v) => `${mention(v)} is nodding 👍`,
	}),
	create_category({
		type: 'gif',
		category: 'nom',
		desc: 'Nom',
		mentioning: false,
		cb: (v) => `${mention(v)} is omnomnoming 🍔`,
	}),
	create_category({
		type: 'gif',
		category: 'sleep',
		desc: 'Sleep',
		mentioning: false,
		cb: (v) => `${mention(v)} is sleeping 😴`,
	}),
	create_category({
		type: 'gif',
		category: 'dance',
		desc: 'Dance',
		mentioning: false,
		cb: (v) => `${mention(v)} is dancing 💃`,
	}),
];
